---
title: "FFM"
author: "Paul Apivat Hanvongse"
date: "9/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

Setup

```{r, include=FALSE}
#R version 4.0.2 (2020-06-22)
#Platform: x86_64-apple-darwin17.0 (64-bit)
#Running under: macOS Catalina 10.15.6
sessionInfo()

# library
library(tidyverse)
```

## Load & Clean Data

Sometimes a CSV file will have all columns bunched together and we want to load the file while having all columns separated. We'll need to use `read.csv` instead of `readr` or `read_csv`.

See this stack overflow for more [details](https://stackoverflow.com/questions/27585857/reading-a-file-in-r-columns-are-separated-with-multiple-space).

```{r, include=FALSE}
# note: setwd() to Desktop
# note: read.csv(header = FALSE) to get rid of 'duplicate row names error', fix later

data <- read.csv("./RData/IPIP-FFM-data-8Nov2018/data-final.csv", header = FALSE, strip.white = T, sep = '')
glimpse(data)

# Turn first row into column name

# Step 1: copy 1st row to header
names(data) <- data[1,]

# Step 2: delete first row
data <- data[-1,]


# NEXT STEP: Add ID column
```

## Quick Viz

Visualizing two survey ITEMS. 

```{r, include=FALSE}

# Uninformative scatter plot
data %>%
    select(EXT1, EXT2) %>%
    mutate(
        EXT1 = as.numeric(EXT1),
        EXT2 = as.numeric(EXT2)
    ) %>%
    ggplot(aes(x = EXT1, y = EXT2)) +
    geom_point()


# Quick Group and Tally
# Visualizing a SINGLE survey item using Bar plot
data %>%
    select(EXT1, EXT2) %>%
    mutate(
        EXT1 = as.numeric(EXT1),
        EXT2 = as.numeric(EXT2)
    ) %>%
    group_by(EXT1) %>%
    tally(sort = TRUE) %>%
    ggplot(aes(x = EXT1, y = n)) +
    geom_col() +
    scale_x_continuous(seq(1,5))


```

NEXT STEP: Add ID column